### ISSUE TITLE
Users in users table all have the same shopID

### ISSUE THREAD

**Issue by callmejamie** [callmejamie/innceedash#2]
Why does all the user records in the users table have the same shopID? That shouldn't be the case.. each user account's shopID should be unique.

**Comment by marklauyq** [comment]
For the time being i made them the same because i needed to test the dashboard using Desmonds data. There are methods that will make sure it won't happen to other accounts.

**Comment by callmejamie** [comment]
OK.. Cos right now its screwing up the accounts data and the subsequent data jobs.. Can u correct it and just use the admin@inncee.com email to login


regards,

Jamie






On Sun, Dec 6, 2015 at 10:50 PM -0800, "marklauyq" <notifications@github.com> wrote:





For the time being i made them the same because i needed to test the dashboard using Desmonds data. There are methods that will make sure it won't happen to other accounts.

---

**Comment by marklauyq** [comment]
Updated
